[package]
name = "mips_asm"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]

[profile.dev]
panic = "abort"
debug = true
opt-level = 0

[profile.release]
panic = "abort"
debug = true
opt-level = 1
